image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Dev Server
    init: yarn
    command: yarn dev
  - name: E2E Cy
    command: |
      gp await-port 3000
      yarn cy:open
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
