#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

nx affected:lint  --parallel=true   # LINTING
nx affected:test  --parallel=true    # UNIT TESTS
yarn nx run-many --target=type-check --all --parallel=true #TYPE CHECKING